### ISSUE TITLE
Latest wine builds fail to install Steam

### ISSUE THREAD

**Issue by strycore** [lutris/buildbot#1]
Latest builds from 1.7.52 to 1.7.55 (and maybe earlier builds) fail to finish updating Steam, it displays an error dialog saying the Steam installation is not valid and asks to reinstall Steam.

I've temporally replaced build 1.7.55 with PlayOnLinux's build which is not affected by this problem.

@Xodetaetl, @qparis and @mulx, if you have any clue what's going on, that would be really helpful. Our build script is located here: https://github.com/lutris/buildbot/blob/master/runners/wine/build.sh and we build on a Ubuntu 14.04 32bit container.

**Comment by qparis** [comment]
Can you provide the build log?

**Comment by qparis** [comment]
Make sure that find . -type f -exec strip {} \; does not strip the fakedlls files. Since Jessie's version of strip, this would break wineprefix creation

**Comment by strycore** [comment]
I should re-run a build to get the log. I admit that the way we strip files is very brutal (it tries to strip every single file in the build) but I have noticed issues with the prefixes creation, most probably because the version of strip in Ubuntu 14.04 must be older than Jessie's.

**Comment by qparis** [comment]
What is your strip version?

**Comment by strycore** [comment]
GNU strip (GNU Binutils for Ubuntu) 2.24

**Comment by qparis** [comment]
A last one: 
$ hexdump -C fakedlls/d3d9.dll | head

**Comment by strycore** [comment]
```
00000000  4d 5a 90 00 03 00 00 00  04 00 00 00 ff ff 00 00  |MZ..............|
00000010  b8 00 00 00 00 00 00 00  40 00 00 00 00 00 00 00  |........@.......|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 80 00 00 00  |................|
00000040  0e 1f ba 0e 00 b4 09 cd  21 b8 01 4c cd 21 54 68  |........!..L.!Th|
00000050  69 73 20 70 72 6f 67 72  61 6d 20 63 61 6e 6e 6f  |is program canno|
00000060  74 20 62 65 20 72 75 6e  20 69 6e 20 44 4f 53 20  |t be run in DOS |
00000070  6d 6f 64 65 2e 0d 0d 0a  24 00 00 00 00 00 00 00  |mode....$.......|
00000080  50 45 00 00 4c 01 03 00  03 00 05 00 00 00 00 00  |PE..L...........|
00000090  00 00 00 00 e0 00 0e 23  0b 01 02 18 00 02 00 00  |.......#........|
```

**Comment by qparis** [comment]
As expected, the DLL is damaged by the split command.

**Comment by strycore** [comment]
Ok, I'll limit the strip command to wine's binaries (unless there are other things that can be safely stripped?)

**Comment by strycore** [comment]
all right! I've rebuild the latest version and tried a complete install of wine + steam + a game and all went perfectly. 
Thanks a lot for your help :)

**Comment by qparis** [comment]
librairies outside fakedll can be safely striped

**Comment by strycore** [comment]
yup, that's what I'm doing now:

```
find ${dest_dir}/bin -type f -exec strip {} \;
find ${dest_dir}/lib -name "*.so" -exec strip {} \;
```
