### ISSUE TITLE
Can't enable Esync in Proton with Lutris v0.5.4

### ISSUE THREAD

**Issue by Chreech** [lutris/buildbot#108]
Esync was working fine with steam proton versions in previous v0.5.3 Lutris build but now it gives message that Esync is not supported with them.

**Comment by tannisroot** [comment]
Esync is enabled in Proton by default.

**Comment by Chreech** [comment]
Nope it is not running games with esync enabled at all. In the earlier
version 0.5.3 it was able to use esync in protons and there was difference
in performance.
