### ISSUE TITLE
RetroArch Cores

### ISSUE THREAD

**Issue by RobLoach** [lutris/buildbot#11]
Could do something like this:
https://github.com/RobLoach/buildbot/blob/18223d2b07b0e00832d0e33f1be24fdf8a4a6d42/runners/retroarch/build.sh#L48-L52

http://buildbot.libretro.com/nightly/ provides a lot of the builds for the cores.

**Comment by strycore** [comment]
Nope, the script is already ready to build cores by itself, I would prefer to ship core that have been built with the same toolchain as RetroArch. I know that the builds from RetroArch are compatible but it's a personnal preference to have control over what we ship.
Still not sure how we're going to distribute RetroArch and the cores, what I'm 100% sure of is that the list of cores we provide will be *way* smaller than the one you proposed. We're not providing every possible libretro core but only a curated subset of them. If people want to download the remaining cores from within RetroArch they have every right to do so but it's not part of Lutris

**Comment by RobLoach** [comment]
Ship all the build cores with the retroarch binary?

**Comment by RobLoach** [comment]
Here's a list of the cores I enjoy most:

beetle-bsnes beetle-wswan beetle-psx beetle-saturn desmume genesis-plux-gx, mupen64plus mame mgba nestopia nxengine ppsspp prboom reicast snes9x

**Comment by strycore** [comment]
Seems reasonable, but it seems that there are 2 SNES cores, we'd have to settle on one. beetle-psx is one I really want to ship when they finish working on the hi-res renderer but so far, I've had better experience with pcsx-rearmed. 

As for shipping the cores, I'm thinking something between how we ship the runtime and wine versions,

**Comment by RobLoach** [comment]
> seems that there are 2 SNES cores

oops. Either are good.

> how we ship the runtime and wine versions

Wine versions? libretro doesn't need wine. You thinking of shipping no cores, and having the user manually download them individually? I think it would make more sense, and likely be simpler, to just ship all of our selected cores with the runtime.

**Comment by strycore** [comment]
I meant the way we handle Wine version with the dialog that allows to install and uninstall each individual versions. We could bundle everything in a single package but that will be very heavy for slow connections.
