### ISSUE TITLE
Final Fantasy XIV crash with Lutris runtime 

### ISSUE THREAD

**Issue by GovanifY** [lutris/buildbot#142]
First of all, sorry if this is the wrong place to post this, I followed the documentation at https://github.com/lutris/docs/blob/master/LutrisRuntime.md although I'm not sure this bug would apply to this issue tracker.

I am running under NixOS, using the latest wine staging 6.12 available for the distribution.
FFXIV do seem to run fine as long as you disable the Lutris Runtime, otherwise you'll end up with a nullptr exec as seen below:

https://hastebin.com/nemowikula.yaml

I am using AMDGPU/mesa with a RX580 gpu.

**Comment by tannisroot** [comment]
Hi, does this issue occur with lutris-6.10-7?

**Comment by GovanifY** [comment]
Yeah, just reproduced:
https://hastebin.com/umiyusihok.yaml

**Comment by tannisroot** [comment]
Can you enable debug logging and create a new log with the crash?

**Comment by GovanifY** [comment]
Sure, sorry for the delay! 
https://hastebin.com/rizofovapa.yaml

Doesn't seem to change much, I did change "Output debugging info" in the runner options to Enabled, Full lists every call wine does to the winapi, which was to a point where Show logs wouldn't even open.

If you still want it nonetheless I'll make it print that on stdio

**Comment by tannisroot** [comment]
Hi, sorry that I only now noticed that you replied, but all the links are dead.

**Comment by GovanifY** [comment]
Hi, 
No issue! The runtime seems to load fine on EndWalker now, so closing this issue :)
