### ISSUE TITLE
Missing i386 libraries for PCSX2 runner.

### ISSUE THREAD

**Issue by junglized** [lutris/buildbot#152]
Hi everyone,

I encountered a problem. A few i386 libraries are missing for PCSX2 runner to run.
![Zrzut ekranu z 2021-06-25 12-20-35](https://user-images.githubusercontent.com/26525585/123420114-05e9c200-d5b3-11eb-9f4f-45c07b550c70.png)
Could anyone help me obtaining them? I found few similar topics on the web but none of them worked unfortunately. Some of them adviced installing standalone PCSX2 emulator but that would defeat a need for having such runner in Lutris on the first place.

**Comment by matmicha** [comment]
I'm also encountering this issue on Pop_OS 22.04, is there a solution or a workaround to this ?

**Comment by junglized** [comment]
I actually forgot I posted this TBH. The only way to make it work is to install missing libraries from [Ubuntu package repo](https://packages.ubuntu.com/). Just look for relevant libraries within the contents of packages. When you find relevant packages install them with `sudo apt install name-of-the-package`. For `libgdk-x11-2.0.so.0` the command would be `sudo apt install libgtk2.0-0:i386`, and so on. Mind that we're missing i386 libraries, so you need to add `:i386` at the end of every terminal command. I wrote about this on [Lutris forum](https://forums.lutris.net/t/pcsx2-cant-find-i386-libraries/11987/12?u=junglized).
