### ISSUE TITLE
Lutris doesn't install dependencies for you

### ISSUE THREAD

**Issue by romulasry** [lutris/buildbot#156]
### Bug description

Lutris should ask to install depedencies (I use Fedora 25) for example.

### How to Reproduce

1. Go to try to Install League of Legends
2. Click on Install

It will then ask to install openssl instead of doing that for you.

### Expected behavior

Install openssl (or needed dependencies)l for you.

### Log output

```shell
N/A
```

### System Information

```shell
[System]
OS:              Fedora Linux 35 
Arch:            x86_64
Kernel:          5.14.17-301.fc35.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD FX(tm)-8320 Eight-Core Processor
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             31.2 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.42.0, 5.14.17-301.fc35.x86_64, LLVM 13.0.0)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.2.5
OpenGL Core:     4.6 (Core Profile) Mesa 21.2.5
OpenGL ES:       OpenGL ES 3.2 Mesa 21.2.5
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game, an installer script or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by tannisroot** [comment]
I can add openssl to runtime

**Comment by romulasry** [comment]
Also where do I report bugs for League of Legend? It runs slow on Fedora 35...

**Comment by tannisroot** [comment]
Is there a particular error message that you get indicating openssl is a requirement for league?

**Comment by tannisroot** [comment]
> Also where do I report bugs for League of Legend on Lutris? It runs slow on Fedora 35...

lutris/wine and you need to elaborate on "runs slow"

**Comment by romulasry** [comment]
2021-11-17 19:06:27,928: This installer requires openssl on your system

**Comment by romulasry** [comment]
> > Also where do I report bugs for League of Legend on Lutris? It runs slow on Fedora 35...
> 
> lutris/wine and you need to elaborate on "runs slow"

It takes a long time for the client to show up.

**Comment by romulasry** [comment]
[textlogfile.log](https://github.com/lutris/buildbot/files/7559653/textlogfile.log)

**Comment by romulasry** [comment]
utris-wrapper: League of Legends
Started initial process 8869 from gamemoderun /home/ryan/.local/share/lutris/runners/wine/lutris-ge-lol-6.16-3-x86_64/bin/wine /home/ryan/Games/league-of-legends/drive_c/Riot Games/Riot Client/RiotClientServices.exe --locale=en_US
Start monitoring process.
gamemodeauto: 
esync: up and running.
abi.vsyscall32 = 0
LeagueClientUx pid: 9426
Waiting for port 34263

**Comment by romulasry** [comment]
2021-11-17 19:12:58,158: Unable to load libGLX_nvidia.so.0
2021-11-17 19:12:58,158: Unable to locate libGLX_nvidia

I don't use nvidia though...
