### ISSUE TITLE
buildbot uses a very outdated repository for Serious Sam: The Second Encounter

### ISSUE THREAD

**Issue by tx00100xt** [lutris/buildbot#170]
buildbot uses a very outdated repository for Serious Sam: The Second Encounter.
https://github.com/lutris/buildbot/blob/master/games/serious-sam/build.sh
At the moment, the code is not building and build-linux.sh is not in the repository.

buildbot uses version based on the source code from 2016 when Ryan Gordon started porting, based on the source code released by Croteam and its old port. Unfortunately, his project has been inactive since autumn 2016.
You can use the game's source code for Serious Sam: The Second Encounter and Serious Sam: The Second Encounter from here.

Source:
https://github.com/tx00100xt/SeriousSamClassic

**Comment by strycore** [comment]
I updated the build script and the installers
