### ISSUE TITLE
Fail to start pcsx2 on Manjaro

### ISSUE THREAD

**Issue by TheAquaSheep** [lutris/buildbot#171]
There is a missing 32-bit library: libnotify.so.4.

`[home]/.local/share/lutris/runners/pcsx2/PCSX2: error while loading shared libraries: libnotify.so.4: wrong ELF class: ELFCLASS64`
Only the 64-bit library is available through the repositories (without AUR).
It is also not possible to run this using system libraries due to version differences.

Is it possible to add this to the runtime?

Thank you.

**Comment by legluondunet** [comment]
fixed!
Now we use pcsx2 AppImage.
