### ISSUE TITLE
 [Gog Galaxy 1.2 Baldur's Gate 3] No sound + lutris does not recognize game is installed (+ black larian launcher)

### ISSUE THREAD

**Issue by GrgMdmn** [lutris/buildbot#174]
Hello ! I have encountered some problems installing and trying to launch baldur's gate 3 on GoG, using Lutris.
The Wine version I am using is "lutris-GE-Proton8-13-x86_64" that I have installed thanks to ProtonUp_Qt.

First of all, I have chosen "Gog Galaxy 1.2" option to install BG3. A Windows GoG launcher has been installed and then I have installed BG3 thanks to that launcher. I have been able to launch the game, but I had no sound.
After having shut down the game, I have closed the launcher, but lutris installation process was endlessly running without considering any installation to have been completed :

![image](https://github.com/lutris/buildbot/assets/68954220/cd28a1f7-4bee-4a84-9df7-14eeb531b46a)

No choice but to click on "quit" (= "abandonner", sorry for the french layout). 
![image](https://github.com/lutris/buildbot/assets/68954220/b9535597-6963-4f4f-8e1b-195e44187046)
Even after having unchecked the "delete games files" box, lutris does not detect any game.
After that, with the kept files, if I try to launch the game, then I have a "new" installation that is launched, but fails because files are already existing. The process tries to update the gog client to 2.0 (but fails: that's logical because we  need to stay at 1.2 version)... And nothing more. 

So that was all for my first time. After that, I manually deleted all the files in /home/me/Games/gog/baldurs-gate-3 but kept the "windows files" in /home/me/Games/gog/baldurs-gate-3/drive_c/Program Files (x86)/GOG Galaxy/Games/Baldurs Gate 3/ in order to accelerate the new installation. 
I then tried to reinstall BG3 another time, using the 1.2 Gog Galaxy option, and as soon as the GOG launcher is installed, I have pasted the "windows files" at the same path. No problem, they were detected by the GoG Launcher, so the installation was very fast. 
However, now, when I am launching the game, the Larian Launcher is all black, so I cannot self-identify and launch the game.
![image](https://github.com/lutris/buildbot/assets/68954220/87a1dcbc-5190-4a02-88b2-b3b663ef80e7)
After having forcely closed the larian launcher and the GoG Galaxy launcher, I have the same Lutris Error : no installation is completed, I only can cancel the installation (exactly as it is on the first screenshot on this post).

Can someone please help me ? ^^'

**Comment by danieljohnson2** [comment]
I haven't a clue, but there might be one in the debug output. Run lutris from the terminal like this:

```
lutris -d
```

And give us the terminal spam you get. No promises, but maybe there'll be something in there.

**Comment by GrgMdmn** [comment]
Do you want that I reprocess all after having launched lutris in debug mode or just launch it and  give you the few lines that come after running this command ?

**Comment by danieljohnson2** [comment]
I mean you should re-install like that.

**Comment by danieljohnson2** [comment]
That does not like right. I see this:
```
DEBUG    2023-08-08 22:52:11,441 [interpreter._iter_commands:349]:Installer command: {'copy': {'src': '95459', 'dst': '$GAMEDIR/extras'}}
```

I don't understand how 95459 is a sensible source; I guess that's what does not exist.

I'll look at this.

**Comment by GrgMdmn** [comment]
Thank you, sir ! :)

**Comment by strycore** [comment]
> I don't understand how 95459 is a sensible source; I guess that's what does not exist.

the destination is $GAMEDIR/extra so 95459 is probably the ID of one of GOG's extra files. I doubt they have their place in an installer using Galaxy.

**Comment by strycore** [comment]
@GrgMdmn I don't know how we can make the message clearer:

![image](https://github.com/lutris/buildbot/assets/280336/aa3b16f7-d27b-402c-bff7-46d422b23ad3)

**Comment by strycore** [comment]
@GrgMdmn if you want to keep the GOG install files: 
![image](https://github.com/lutris/buildbot/assets/280336/9d1a11a0-269d-436a-8aa6-d69ce5e44276)

Then again, that's not gonna happen in your case, since you're using Galaxy.

**Comment by GrgMdmn** [comment]
> @GrgMdmn I don't know how we can make the message clearer:
> 
> ![image](https://user-images.githubusercontent.com/280336/259261329-aa3b16f7-d27b-402c-bff7-46d422b23ad3.png)

Thank you for answering ! Just to be clear : when I am starting a new installation, installation folder has been cleared. I install the GoG Galaxy Launcher and only after that, I paste the windows files in the windows path. So when installing the launcher, I do not have this message since the installation path is empty.

So I cannot configure a download cache since there is no path to fill in this field with.

**Comment by GrgMdmn** [comment]
> @GrgMdmn I don't know how we can make the message clearer:
> 
> ![image](https://user-images.githubusercontent.com/280336/259261329-aa3b16f7-d27b-402c-bff7-46d422b23ad3.png)

Thank you for answering ! Just to be clear : when I am starting a new installation, installation folder has been cleared. I install the GoG Galaxy Launcher and only after that, I paste the windows files in the windows path. So when installing the launcher, I do not have this message since the installation path is empty.

So I cannot configure a download cache since there is no path to fill in this field with.

**Comment by strycore** [comment]
The download cache is used when Lutris is used to download the GOG game files. If you're using GOG Galaxy, then Lutris won't have any knowledge of the Baldur's Gate 3 files. At best, Lutris will cache the GOG Galaxy installer. 

Now, if you're keeping BG3 files from a previous install and moving them to a new GOG Galaxy install, that's a valid strategy, as long as Galaxy is able to find existing files. (I don't have much experience with Galaxy since I only use Lutris for GOG but most game launchers support detecting game files)

**Comment by GrgMdmn** [comment]
Setting the download cache to the path /home/me/Games/gog/baldurs-gate-3 only forces lutris to keep the GoG 1.2 Launcher Installer .exe file (around 200 MB)... If I try to reinstall BG3 using Lutris and by typing the cache path, it only spares me the GoG Lancher download... And then, it crashes without running any Galaxy Launcher

**Comment by strycore** [comment]
Don't set the cache path to where the game is being installed. That will, as you have just experienced, make the install fail. Use another, empty location for the cache. 

If you want to download the files for BG3, you have to use the GOG (Auto) installer or use the GOG integration in Lutris. As I said earlier, there is no way for Lutris to know how to cache GOG Galaxy downloads.

**Comment by GrgMdmn** [comment]
Thank you for your answer.

About the first installing case, when installing gog galaxy 1.2 launcher, I want to do so in order to keep the game updated because I am not sure that Gog (auto) will keep the game updated.

I will try the 2 solutions, but in about two weeks because I am on holiday.
I keep you updated

**Comment by strycore** [comment]
When the game is installed with Lutris and without Galaxy, is doesn't update automatically. 
It is however possible to install updates and DLC manually from Lutris.
Cloud saves from GOG Galaxy won't be available.

**Comment by GrgMdmn** [comment]
Ok so I will focus on the first solution you gave me, since I would like the game to be automatically updated

**Comment by GrgMdmn** [comment]
Hello there. After some time, I have tried again to reinstall BG3 using Lutris. I have updated my lutris version and wine too (now it is Proton 8.17).

I have been able to install BG3 and playing it, using the GoG 1.2  option. Everything is working fine, except that after exiting the game and exiting the launcher, the installing lutris window is still here. And if I click on "Abort", it proposes me to cancel the installation... Too bad, this is the only thing that does not work for me :(

**Comment by GrgMdmn** [comment]
![Screenshot_20231001_122936](https://github.com/lutris/buildbot/assets/68954220/e0c2c3f5-e31a-4fb9-beaf-9079a4618875)

![image](https://github.com/lutris/buildbot/assets/68954220/49c3b02b-88c3-4c94-bb4a-c8bede0add35)

**Comment by danieljohnson2** [comment]
Hang on; are you playing the game right off the installer? You should try to install it only, then run it from Lutris; that might work better.

It's strange though that you are not seeing a checkbox about removing the files. If there is not one, it should not remove the files. This can happen if you install into an existing directory; perhaps you need to start with no existing directory?

**Comment by GrgMdmn** [comment]
I have played the game right after having installed. But now, I have reinstalled following your advice: just installing, no playing, and then clicking on GoG Galaxy's "Exit" button... I have the exactly same window of Lutris that does not complete the install... :/

About the checkbox that does not appear, after aborting the install, the files are not deleted, but nothing is detected in Lutris, and if I want to relaunch BG3, I will have to install it again... :(

**Comment by danieljohnson2** [comment]
OK, so this is still GOG Galaxy. I misunderstood.

Lutris doesn't know GOG Galaxy installed anything. You can use the "+" in the corner, and then "Add locally installed game" to make the game visible to Lutris.

Or, you could install via Lutris's GOG integration. Activate the GOG source, log in to your account, and use the icon for the game that appears inside Lutris to install it.

**Comment by GrgMdmn** [comment]
Thank you very much, this is working ! 

What I had to do is to add a "game", and add the "GalaxyClient.exe" file. From this, I am able to re-launch the GoG Launcher, keep the game updated and launch it everytime I want. The game is not in the "GoG" tab but that is not a big deal

**Comment by GrgMdmn** [comment]
I have tested installing a game of Epic by using the Epic Game Store Launcher, and after having installed the game, I left the EGS launcher, and Lutris indeed considered the game as installed... For some reason, this manipulation is impossible with GoG :(

**Comment by danieljohnson2** [comment]
Well, I don't know if it's possible, but someone who wants it has to write it even if it is.

**Comment by GrgMdmn** [comment]
What I do no understand is : 
- On one hand when installing Epic games, Lutris Launcher only installs Epic Games Launcher one time, and uses it to install each games. Each time a game is installed using the EGL, it appears in the "Epic Games" Lutris' tab.
- On the other hand, when installing GoG game, Lutris Launcher, installs GoG Galaxy 1.2 then to install a game. After installing, the game is not recognized and listed in the GoG tab (whereas it is for epic). Moreover, I will have to install GoG Galaxy Launcher as many times as I am installing games from the "GoG tab"... Except if I install GoG Galaxy Launcher just one time using one random game installation, then add this launcher as a "game", and use it to install all my games... ^^'

In fact, installing GoG Galaxy Launcher works, and installing games using this launcher works too. I think that is just an organizational problem.

In any case, thank you very much for your help !

**Comment by strycore** [comment]
Do I have to pay people for them to stop using GOG Galaxy? Or make them tacos maybe?

**Comment by GrgMdmn** [comment]
I'm sorry, it's just GoG Galaxy is a good way to keep the games automatically updated ^^'

**Comment by strycore** [comment]
At some point we might have a better update process for GOG games.
We're also going to support cloud saves.
If you rely on those features, Galaxy might be your best bet for now but know that Galaxy has an history of not working great on Linux and I personally don't use it so it receives no testing with Lutris.

**Comment by GrgMdmn** [comment]
Thank you for your answer. Of course, if lutris is able to handle the cloud saves and the updates and patches one day, I will surely not use galaxy. But for the moment, this is the only way I have to use these features.
But, maybe am I wrong, but I do not find that Galaxy is so badly working. It works for me when running it as a "game" and I then can install each game I want from it. The only problem is that it is not very well integrated to lutris for the moment and each game installed from galaxy is not listed in the GoG lutris tab (whereas it is for the epic games installed from the epic launcher)

All the same, thank you again for the help, it is working great for me :)

**Comment by strycore** [comment]
As I've said, I done very little testing with Galaxy. And most software seem to work pretty well with current versions of Wine. It's very likely that the experience with Galaxy is fine today. I remember seeing some scripts warning about issues about Galaxy 1.x VS 2.x.

For the integration, I had the opposite discussion recently. About using Legendary instead of the real EGS client. Right now, we don't have a way to handle several integrations for the same game store. Also, the GOG library is less heterogeneous than EGS where everything runs with Wine. GOG has Linux games, Dosbox games and ScummVM games, with Lutris we can use the respective runners to launch the games. With Galaxy, being a Windows app, it wouldn't make a difference and install Windows versions instead of Linux versions and use their bundled DOSBox and ScummVM in Wine, which is often less optimal than using their native versions.

**Comment by GrgMdmn** [comment]
Ok, I understand your point. In that case having an update process "made in lutris" could be a good thing to both optimize the games performances (in particular the games coded in Linux) and keep the games updated + enabling the cloud saves sync... I suppose this will demand a lot of work, so you have all my support ! 

Thanks again for these discussions :)
