### ISSUE TITLE
image:ubuntu/bionic/i386 is no longer available in the lxc default repository

### ISSUE THREAD

**Issue by SwimmingTiger** [lutris/buildbot#175]
From Wayback Machine, I found that i386 images still exists on June 17, 2023 (https://web.archive.org/web/20230617150457/https://images.linuxcontainers.org/).

But they (and any other architectures except arm64 and amd64) disappeared after July 6th (https://web.archive.org/web/20230706124416/https://images.linuxcontainers.org/).

But I now need an i386 ubuntu image to build wine-ge-custom (https://github.com/GloriousEggroll/wine-ge-custom/blob/master/Vagrantfile#L74).

So is there a mirror with i386 images I can find somewhere, or how do I build it myself?

---

Current status:

```
lxc launch images:ubuntu/bionic/i386 buildbot-bionic-i386
````
> Creating buildbot-bionic-i386
> Error: Failed container creation: The requested image couldn't be found

```
lxc image list images: | awk -F'|' '{print $6}' | grep -vP '^\s*(ARCH)?\s*$' | sort | uniq -c
````
>    280  aarch64 
>    358  x86_64

---

Upstream discussion: https://discuss.linuxcontainers.org/t/where-should-i-look-for-i386-images-that-used-to-exist-on-images-linuxcontainers-org/17827

**Comment by strycore** [comment]
I guess now is the right time to finally get rid of the LXC based setup. 

I suggest the following:
- Migrate to a pure Vagrant based setup, no containerization
- Update from the Ubuntu 18.04 base to Ubuntu 22.04
- Change the virtualbox backend to libvirt

**Comment by strycore** [comment]
Or we could use Gitlab. Wine already has a Gitlab build workflow in place, so we might as well stay close to upstream.

**Comment by strycore** [comment]
On Wine's Gitlab configuration they don't use different environments for 32 and 64 bit https://gitlab.winehq.org/wine/wine/-/blob/master/tools/gitlab/build-linux

Neither did I find any reference to this on the current documentation.
During the last WineConf they said they would eliminate the need for 32bit environments, but it wasn't ready for 8.0. Guess it is ready now. 
If that's the case, this would simplify the build script a lot

**Comment by AdivonSlav** [comment]
Any update on this?

**Comment by GloriousEggroll** [comment]
I've added a workaround for now inside wine-ge-custom:

https://github.com/GloriousEggroll/wine-ge-custom/commit/caeb7993552644e818b3393bf96df3461fd5894a

Please read the README instruction as the setup process has changed slightly.

**Comment by GloriousEggroll** [comment]
closing as fixed. recent commits give option to build using either docker/podman or vagrant without needing LXC for anything
