### ISSUE TITLE
kenshi installer uses broken winetricks dll, aborts

### ISSUE THREAD

**Issue by Baerbeisser** [lutris/buildbot#178]
The kenshi [installer script](https://lutris.net/games/install/11422/view) tries to install borked `vcrun6sp6`, which results in error 256, abort. Seems like the winetricks dependency list is from some old thread from 2017 i stumbled upon shortly ago and lost it again.

Are `vcrun6sp6` *and* `vcrun2010` still needed? As far as i know, new vcrun are just the old one + additional libraries?

Although the game crashes for me on creating a new save with vcrun2022 (with useless error log). What does work?

[lutris-kenshi.log](https://github.com/lutris/buildbot/files/13846607/lutris-kenshi.log)

**Comment by strycore** [comment]
Given how the script installs dxvk with winetricks, it has likely been written by someone who is absolutely clueless. A lot of winetricks tasks present in scripts are completely unneeded. 

Scripts are maintained by the lutris community so don't hesitate to make edits to existing scripts to improve and fix them.
