### ISSUE TITLE
ppengine

### ISSUE THREAD

**Issue by telanus** [lutris/buildbot#25]
[te_lanus] https://github.com/jonathanopalise/ppengine
[girobot] Title: GitHub - jonathanopalise/ppengine: 3D remake of Ataris Pole Position coin-op, using game logic reverse engineered from the arcade ROMs (at github.com)
[strycore] te_lanus, neat! can you create an issue in the buildbot repo so I remember to build it?

**Comment by strycore** [comment]
thanks!

**Comment by strycore** [comment]
I added a build script for it but the build fails so either the scripts needs fixing or the engine itself does.
