### ISSUE TITLE
Wine Staging 2.16 - Open link in system browser fails with Runtime enabled.

### ISSUE THREAD

**Issue by IngeniousDox** [lutris/buildbot#27]
Playing: World of Warcraft. Ubuntu 16.04.

This does not happen when runtime is disabled. Output in terminal:

> /usr/bin/google-chrome-stable: /home/dox/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)
> /usr/bin/google-chrome-stable: /home/dox/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)
> /opt/google/chrome/chrome: /home/dox/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)
> /opt/google/chrome/chrome: /home/dox/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)
> [19381:19418:0914/181838.191961:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
> Aborted (core dumped)
> /usr/bin/x-www-browser: /home/dox/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)
> /usr/bin/x-www-browser: /home/dox/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)
> /opt/google/chrome/chrome: /home/dox/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)
> /opt/google/chrome/chrome: /home/dox/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)
> [19430:19469:0914/181838.768699:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
> Aborted (core dumped)
> 
> (firefox:19476): GLib-ERROR **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmem.c:100: failed to allocate 18446744073271633382 bytes
> ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
> 19481
> ExceptionHandler::SendContinueSignalToChild sent continue signal to child
> Terminated

Testing:

- Renaming "libdus-1.so.3"/"libdbus-1.so.3.5.8" > Did not fix it.

- Renaming ".local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu" > Did not fix it.

- Renaming ".local/share/lutris/runtime/steam/amd64" > Fixed it.

**Comment by strycore** [comment]
we should probably switch libdbus from the Steam runtime to the Ubuntu 16.04 one

**Comment by IngeniousDox** [comment]
I have never bothered to look much at DBUS, but I do get this warning when I start up Lutris: 

> (lutris:2498): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused

I have basically always ignored it. But perhaps you can find some more information out of it for this issue.

**Comment by strycore** [comment]
Should be fixed in 0.4.15, we remove any trace of the runtime when opening a browser now
