### ISSUE TITLE
innoextract is too old for newer GOG games

### ISSUE THREAD

**Issue by daniel-j** [lutris/buildbot#32]
I tried to extract the installer for the [GOG game Jazz Jackrabbit 2](https://www.gog.com/game/jazz_jackrabbit_2_collection). It requires innoextract 1.6 while the one Lutris provides is 1.5.
```
Warning: Unexpected setup data version: 5.5.7 (unicode)
Warning: Unexpected Privileges value: 4
Stream error while parsing setup headers!
```

**Comment by strycore** [comment]
Can use https://lutris.net/files/tools/innoextract-1.7-pre-x86_64.tar.gz for a recent version

**Comment by daniel-j** [comment]
I ended up using http://constexpr.org/innoextract/files/innoextract-1.6-linux.tar.xz from the official download site.

**Comment by daniel-j** [comment]
Did GOG change the way Windows installers are packaged? I can't use innoextract to get the raw files anymore :(
