### ISSUE TITLE
Lutris runtime interferes with VulkanSDK

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/buildbot#39]
I set up a new prefix with Staging 3.4 and Vulkan SDK for testing with DXVK but cube.exe doesn't run unless the runtime is disabled. Here's what it spits out with it on:

![](https://cdn.discordapp.com/attachments/413881848763252740/425390090202906632/Screenshot_from_2018-03-19_13-27-53.png)
![](https://cdn.discordapp.com/attachments/413881848763252740/425392318930092055/Screenshot_from_2018-03-19_13-36-45.png)

Ubuntu 17.10

**Comment by strycore** [comment]
Do you know what part of the runtime causes that? (try renaming runtime/steam to runtime/steam.orig and see if you still have the issue with the runtime enabled)

**Comment by strycore** [comment]
Ok, so it's something in the Steam folder, you can try narrowing it down by moving some stuff out of the steam runtime.

**Comment by AccountOneOff** [comment]
This is the offending lib: 

    /home/cxf/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libvulkan.so.1.0.3

**Comment by strycore** [comment]
It is indeed a bad idea to ship libvulkan… I didn't even know about that. I'll remove it from the runtime.

**Comment by strycore** [comment]
Fixed
