### ISSUE TITLE
vcrun2013 fails to install, needs libpng12.so.0 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by CitrusAlex** [lutris/buildbot#41]
I'm using thesim2-3.7 build from lutris. When I try to execute vcrun2013 installer, in the terminal it returns this
`0034:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng12.so.0`
I am using 18.04. As far as I know, in that version Ubuntu dropped libpng12 and now uses libpng16. Is it possible to fix this? vcrun2013 is quite important for a lot of games.

**Comment by plata** [comment]
Sometimes you can hack around this kind of issues by creating a link `libpng12.so.0 -> libpng16.so.0`. Didn't check if it works for this though.

**Comment by CitrusAlex** [comment]
Even if it does fix it (If I remember correctly, it doesn't?), a hack that is required to be made by user is not a solution.

**Comment by strycore** [comment]
I was able to reproduce the issue and can confirm it's now fixed in master.
