### ISSUE TITLE
SuperTux needs libphysfs1

### ISSUE THREAD

**Issue by RobLoach** [lutris/buildbot#5]
I could be wrong, but SuperTux requires `libphysfs1` in order to run. Is it a dependency that's missed?

**Comment by Xodetaetl** [comment]
You're right and it also misses libsquirrel, which isn't available in any version of Ubuntu. I've tried with the most recent version from OpenSuSE but it complains about missing symbols in the lib, so it was likely built with an even more recent version.

I'm unpublishing the installers until this is solved.

**Comment by strycore** [comment]
?? 
libsquirrel is statically linked into the game's executable, did you get an error regarding this lib?
I'll add libphysfs1 in the runtime, it is indeed a build dependency.

**Comment by strycore** [comment]
libphysfs1 added and installers re-published

**Comment by Xodetaetl** [comment]
> libsquirrel is statically linked into the game's executable, did you get an error regarding this lib?

Yes, but it's just with the 32-bit version. It's looking for libsquirrel.so

**Comment by strycore** [comment]
that's not a big problem, I add commented the inclusion of this lib in the final build but I can put it back, won't affect the 64bit build.

**Comment by strycore** [comment]
I thought it wouldn't be a problem but the libsquirrel.so file isn't there. I have no idea why the 64bit build statically links this lib and the 32bit does not.

**Comment by Xodetaetl** [comment]
Trash the 32-bit version then ?

**Comment by strycore** [comment]
That seems to be the most sensible option for now, I removed the 32bit installer.
