### ISSUE TITLE
Using innoextract 1.7-pre fails

### ISSUE THREAD

**Issue by Skeen** [lutris/buildbot#54]
Hi,

As suggested in #32, a newer version of innoextract is available and required for newer GOG games, however when using https://lutris.net/files/tools/innoextract-1.7-pre-x86_64.tar.gz I get the following error:
```
.../tmp/innoextract/innoextract: error while loading shared libraries: libboost_iostreams.so.1.58.0: cannot open shared object file: No such file or directory
```
I don't know if boost was supposed to be statically linked, or if there is simply a missing path somewhere, running `ldd` yields:
```
skeen@morphine ~/lutrisdev> ldd .../tmp/innoextract/innoextract
	linux-vdso.so.1 (0x00007ffd49710000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fe86bb61000)
	libboost_iostreams.so.1.58.0 => not found
	libboost_filesystem.so.1.58.0 => not found
	libboost_system.so.1.58.0 => not found
	libboost_program_options.so.1.58.0 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe86b7df000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe86b4db000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe86b2c4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe86af25000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe86ad21000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe86ab04000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe86bd87000)
```
My system (Debian Stretch) ships with boost version 1.62.0, so version 1.58.0 is not easily available.

Assuming the libraries are not meant to be statically linked, how should I go about including the appropriate libraries?

**Comment by Skeen** [comment]
For now using @daniel-j's solution https://github.com/lutris/buildbot/issues/32#issuecomment-378370484 works, but it might be preferable to use the same general innoextract tool in scripts.

**Comment by strycore** [comment]
A new runtime should download next time you start lutris, please reopen the issue if you are missing other libs
