### ISSUE TITLE
Ship libx264.so.155 with runtime

### ISSUE THREAD

**Issue by tannisroot** [lutris/buildbot#90]
Because the Wine build is looking for Ubuntu 16.04-specific libx264 library, it won't find one and fail to load xaudio. For example, this is what happen when I launch AC Unity from Uplay:
```
0191:err:module:load_builtin_dll failed to load .so lib for builtin L"xaudio2_7.dll": libx264.so.155: cannot open shared object file: No such file or directory
```
Because of this, audio during intro doesn't work.

**Comment by strycore** [comment]
We can't keep hacking the runtime like that, we have to make our builds successful on Bionic.
Please setup the buildbot locally and see if you can repro the button mapping issue on bionic builds

**Comment by tannisroot** [comment]
The bionic builds seems to work pretty well for me, no gamepad or mapping issues.
