### ISSUE TITLE
Buildbot breaks with each new Faudio release

### ISSUE THREAD

**Issue by tannisroot** [lutris/buildbot#94]
Currently buildbot fails on this when building Wine:
>+ wget https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/amd64/libfaudio0_19.06.07-0~bionic_amd64.deb
--2019-07-26 04:51:52--  https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/amd64/libfaudio0_19.06.07-0~bionic_amd64.deb
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2620:113:80c0:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-07-26 04:51:53 ERROR 404: Not Found.

If you take a look at this page https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/amd64/, you will see that `libfaudio0_19.06.07-0~bionic_amd64.deb` was replaced with `libfaudio0_19.07-0~bionic_amd64.deb`. 
So I think it would be cool if we could avoid manual tinkering and just pick up whatever latest libfaudio that repo has.

**Comment by Guy1524** [comment]
Would nice if the admins of that website made a link to the latest version of faudio they provide.
